import { createGetOptionTextFn } from '@/utils'

export enum SourceType {
  APPLICATION = 'APPLICATION',
  // APPLICATION_FILE = 'APPLICATION_FILE',
  RECEIVE = 'RECEIVE',
  RECEIVE_ASSIGNMENT = 'RECEIVE_ASSIGNMENT',
  SEND = 'SEND',
  SEND_RECORD = 'SEND_RECORD',
  SEND_SINGLE = 'SEND_SINGLE',
  INVESTIGATION = 'INVESTIGATION',
  MEETING = 'MEETING',
  RESOLUTION = 'RESOLUTION',
  APPEAL_RECORD = 'APPEAL_RECORD',
  FAMILY_ABUSE = 'FAMILY_ABUSE',
  LAWSUIT_NOTICE = 'LAWSUIT_NOTICE',
  COURT_NOTICE = 'COURT_NOTICE',
  ARBITRATION_NOTICE = 'ARBITRATION_NOTICE',
  AGENT_PREPAYMENT_REQUEST = 'AGENT_PREPAYMENT_REQUEST',
  AGENT_REPORT = 'AGENT_REPORT',
  AGENT_NO_SERVICE_FEE_RECORD = 'AGENT_NO_SERVICE_FEE_RECORD',
  PAYMENT_NOTICE_ARBITRATION = 'PAYMENT_NOTICE_ARBITRATION',
  PAYMENT_NOTICE_AGENT = 'PAYMENT_NOTICE_AGENT',
  REFUND_RECORD = 'REFUND_RECORD',
  BUSINESS_SUBMIT = 'BUSINESS_SUBMIT',
  BUSINESS_RESULT = 'BUSINESS_RESULT',
  CONSULTATION = 'CONSULTATION',
  APPLICATION_SUBMIT_OBJECT = 'APPLICATION_SUBMIT_OBJECT',
  APPLICATION_VOUCHER = 'APPLICATION_VOUCHER',
  APPLICATION_SUPPLEMENT = 'APPLICATION_SUPPLEMENT',
}

export const useSourceTypeHelpers = () => {
  const sourceTypeEnumOptions = [
    { value: SourceType.APPLICATION, label: '申請個案' },
    // { value: SourceType.APPLICATION_FILE, label: '申請個案_文件' },
    { value: SourceType.RECEIVE, label: '收件' },
    { value: SourceType.RECEIVE_ASSIGNMENT, label: '收件_分派記錄' },
    { value: SourceType.SEND, label: '發件' },
    { value: SourceType.SEND_RECORD, label: '寄件資料' },
    { value: SourceType.SEND_SINGLE, label: '發件_單獨發件' },
    { value: SourceType.INVESTIGATION, label: '調查內容' },
    { value: SourceType.MEETING, label: '會議記錄' },
    { value: SourceType.RESOLUTION, label: '決議' },
    { value: SourceType.APPEAL_RECORD, label: '司法申訴' },
    { value: SourceType.FAMILY_ABUSE, label: '家暴' },
    { value: SourceType.LAWSUIT_NOTICE, label: '律師公會通知' },
    { value: SourceType.COURT_NOTICE, label: '法院通知' },
    { value: SourceType.ARBITRATION_NOTICE, label: '仲裁機構通知' },
    { value: SourceType.AGENT_PREPAYMENT_REQUEST, label: '代理人預付請求' },
    { value: SourceType.AGENT_REPORT, label: '代理人報告' },
    {
      value: SourceType.AGENT_NO_SERVICE_FEE_RECORD,
      label: '代理人不收服務費記錄',
    },
    {
      value: SourceType.PAYMENT_NOTICE_ARBITRATION,
      label: '付款通知_仲裁機構',
    },
    { value: SourceType.PAYMENT_NOTICE_AGENT, label: '付款通知_代理人' },
    { value: SourceType.REFUND_RECORD, label: '退款記錄' },
    { value: SourceType.BUSINESS_SUBMIT, label: '業務遞交物' },
    { value: SourceType.BUSINESS_RESULT, label: '業務結果物' },
    { value: SourceType.CONSULTATION, label: '諮詢' },
    { value: SourceType.APPLICATION_SUBMIT_OBJECT, label: '申請個案-遞交文件' },
    { value: SourceType.APPLICATION_VOUCHER, label: '申請個案-申請憑證' },
    { value: SourceType.APPLICATION_SUPPLEMENT, label: '申請個案-補交資料' },
  ]
  const getSourceTypeText = createGetOptionTextFn(sourceTypeEnumOptions)
  return { sourceTypeEnumOptions, getSourceTypeText }
}
